Replace zip-rs with lz4-compress
`zip` implements bzip2 and deflate compression algorithms.
Unfortunately the crates implementing those algorithms cannot be
cross-compiled to WASM.

I could compile `zip` to WASM without those features. But for my app
I need compression.

Therefore I replaced `zip` with `lz4-compression`.

I also looked into `rust-lzma`. Unfortunately the library failed to
compile for target `wasm32-unknown-unknown`:

$ cargo build --target wasm32-unknown-unknown
Compiling rust-lzma v0.5.1
error: failed to run custom build command for `rust-lzma v0.5.1`

Caused by:
  process didn't exit successfully: `/home/developer/projects/servus/target/debug/build/rust-lzma-bea4a5ae37d12dce/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Could not find liblzma using pkg-config', /home/developer/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-lzma-0.5.1/build.rs:10:3

`cargo build` for the default target works though. So I am wondering
if this problem is fixable. Is `pkg-config` looking at the wrong
places when it searches for `liblzma`? And can I maybe manually
cross-compile `liblzma` to WASM?